import{chromium}from'../../../frontend/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const base='http://127.0.0.1:3004',out=new URL('.',import.meta.url).pathname,b=await chromium.launch(),checks=[],errors=[];let complete=false;const record=(name,data)=>{checks.push({name,data});console.log(name,JSON.stringify(data||{}));};
async function login(id){const p=await b.newPage({viewport:{width:1280,height:1000}});p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await p.goto(base+'/login');await p.getByLabel('Student ID').fill(id);await p.getByLabel('Password',{exact:true}).fill('StudentPass!2026');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(base+'/');await p.locator('.product-shell').waitFor();const headers={Authorization:'Bearer '+await p.evaluate(()=>sessionStorage.getItem('mis_sim.access_token'))};const me=await(await p.request.get(base+'/api/auth/me',{headers})).json();return{p,headers,me};}
async function call(u,method,path,data,expected=200){const r=await u.p.request.fetch(base+'/api'+path,{method,headers:u.headers,data});assert.equal(r.status(),expected,method+' '+path+' '+await r.text());return r.json();}
try{const a=await login('M2-101'),peer=await login('M2-102'),other=await login('M2-105'),cross=await login('M2-201');const p=a.p,root='/instances/'+a.me.instance_id;record('Four browser logins + same-origin auth canary',[a.me,peer.me,other.me,cross.me].map(m=>({student:m.student_id,instance:m.instance_id})));
await p.getByRole('link',{name:/Infrastructure/}).click();await p.getByRole('button',{name:'+ New Host Platform',exact:true}).first().click();await p.locator('.host-platform-form select').first().selectOption('on_prem');await p.getByLabel('Name',{exact:true}).fill('Scope audit host');const w=p.waitForResponse(r=>r.url().endsWith('/host-platforms')&&r.request().method()==='POST');await p.getByRole('button',{name:'Create',exact:true}).click();const cr=await w;assert.equal(cr.status(),200);const host=(await cr.json()).platforms.find(h=>h.name==='Scope audit host');assert.ok(host);const hp=root+'/host-platforms/'+host.id;await p.getByText('Scope audit host',{exact:true}).click();await p.locator('.platform-detail-modal').waitFor();await p.screenshot({path:out+'created.png',fullPage:true});record('Browser host create',host);
const rollout=await call(a,'GET',root+'/rollout'),asset=rollout.team.deployments[0];let added=await call(a,'POST',hp+'/members',{asset_key:asset.id,member_kind:'component'});let member=added.platforms.find(h=>h.id===host.id).members[0];assert.equal(member.asset_key,asset.id);assert.deepEqual(Object.keys(member).sort(),['asset_key','assigned_round','id','member_kind']);record('Add real initialized asset; response contract preserved',member);
let renamed=await call(a,'PATCH',hp,{name:'Scope audit renamed'});assert.equal(renamed.platforms.find(h=>h.id===host.id).name,'Scope audit renamed');const visible=await call(peer,'GET',root+'/host-platforms');assert.equal(visible.platforms.find(h=>h.id===host.id).members[0].id,member.id);record('Rename and same-team member read');
const ownOther=await call(other,'GET',root+'/host-platforms?team_id='+host.team_id);assert.equal(ownOther.platforms.length,0);const crossOwn=await call(cross,'GET','/instances/'+cross.me.instance_id+'/host-platforms');assert.equal(crossOwn.platforms.length,0);
for(const u of [other,cross]){const expected=u===other?404:403;await call(u,'PATCH',hp,{name:'Forbidden'},expected);await call(u,'POST',hp+'/members',{asset_key:asset.id,member_kind:'component'},expected);await call(u,'DELETE',hp+'/members/'+member.id,undefined,expected);}
await call(cross,'GET',root+'/host-platforms',undefined,403);const controlsOther=await call(other,'GET',root+'/rollout');assert.ok(controlsOther.team.deployments.every(d=>d.platform_id!==host.id));const controlsCross=await call(cross,'GET','/instances/'+cross.me.instance_id+'/rollout');assert.ok(controlsCross.team.deployments.every(d=>d.platform_id!==host.id));record('Populated cross-team404/cross-instance403 mutations and no rollout leakage');
let removed=await call(a,'DELETE',hp+'/members/'+member.id);assert.equal(removed.platforms.find(h=>h.id===host.id).members.length,0);assert.ok((await call(a,'GET',root+'/rollout')).team.deployments.every(d=>d.platform_id!==host.id));record('Owner removal reflected in list and rollout');
added=await call(a,'POST',hp+'/members',{asset_key:asset.id,member_kind:'component'});member=added.platforms.find(h=>h.id===host.id).members[0];await p.goto(base+'/rollout');await p.getByRole('button',{name:/^view/}).click();await p.locator('.platform-detail-modal').waitFor();assert.match(await p.locator('.platform-detail-modal').innerText(),/Scope audit renamed/);assert.ok((await p.locator('.platform-detail-modal').innerText()).includes(asset.label));assert.equal(await p.getByRole('button',{name:'+ Add a Service',exact:true}).count(),0);await p.screenshot({path:out+'rollout-readonly.png',fullPage:true});record('Re-added scoped member visible in read-only rollout modal');
await p.goto(base+'/review');const lock=p.waitForResponse(r=>r.url().endsWith('/review/lock'));await p.getByRole('button',{name:'Lock round',exact:true}).click();assert.equal((await lock).status(),200);await call(a,'PATCH',hp,{name:'Locked forbidden'},409);await call(a,'POST',hp+'/members',{asset_key:rollout.team.deployments[1].id,member_kind:'component'},409);await call(a,'DELETE',hp+'/members/'+member.id,undefined,409);const retained=await call(a,'GET',root+'/host-platforms');assert.equal(retained.platforms.find(h=>h.id===host.id).members[0].id,member.id);assert.equal(retained.platforms.find(h=>h.id===host.id).name,'Scope audit renamed');await p.goto(base+'/infrastructure');await p.locator('.product-shell').waitFor();assert.equal(await p.getByRole('button',{name:'+ New Host Platform',exact:true}).count(),0);await p.setViewportSize({width:720,height:1000});await p.goto(base+'/rollout');await p.getByRole('button',{name:/^view/}).click();await p.locator('.platform-detail-modal').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);await p.screenshot({path:out+'locked-720.png',fullPage:true});record('Browser lock retains read-only member and blocks rename/add/remove409');assert.deepEqual(errors,[]);complete=true;
}finally{await writeFile(out+'results.json',JSON.stringify({complete,checks,errors},null,2));await b.close();}
