import {chromium} from '../../../frontend/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
const out=new URL('.',import.meta.url).pathname,base='http://127.0.0.1:3004';const browser=await chromium.launch();const p=await browser.newPage({viewport:{width:1280,height:1000}});p.setDefaultTimeout(60000);const results=[];
const save=async(path,name)=>{const w=p.waitForResponse(r=>r.url().endsWith(path)&&r.request().method()==='PATCH');await p.getByRole('button',{name,exact:true}).click();const r=await w;const data=await r.json();if(r.status()!==200)throw Error(JSON.stringify(data));return data;};
try{
await p.goto(base+'/login');await p.getByLabel('Student ID').fill(process.env.REVIEW_LOGIN || 'M2-105');await p.getByLabel('Password',{exact:true}).fill('StudentPass!2026');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(base+'/');await p.locator('.product-shell').waitFor();const token=await p.evaluate(()=>sessionStorage.getItem('mis_sim.access_token'));const headers={Authorization:`Bearer ${token}`};const me=await(await p.request.get(base+'/api/auth/me',{headers})).json();const prefix=base+'/api/instances/'+me.instance_id;const controls=await(await p.request.get(prefix+'/controls',{headers})).json();const seeded=await p.request.patch(prefix+'/controls/people',{headers,data:{version:1,expected_revision:controls.team.revision,commands:[{key:'comm_store',op:'communicate',org_unit:'store_operations',option:'none'},{key:'comm_finance',op:'communicate',org_unit:'finance',option:'none'}]}});if(seeded.status()!==200)throw Error(await seeded.text());const seededView=await seeded.json();const clear=await p.request.patch(prefix+'/components',{headers,data:{version:1,expected_revision:seededView.team.revision,replace_categories:{application:[]}}});if(clear.status()!==200)throw Error(await clear.text());
await p.goto(base+'/infrastructure');await p.getByRole('tab',{name:'People',exact:true}).click();await p.getByLabel('Hiring option').selectOption({index:1});await p.getByLabel('Unit').selectOption('store_operations');let data=await save('/controls/people','Save people decisions');results.push({case:'Partial Unit selection while hiring removes prior store communication',commands:data.team.selected_commands,preserved:data.team.selected_commands.some(c=>c.op==='communicate'&&c.org_unit==='store_operations')});await p.screenshot({path:out+'communication-loss.png',fullPage:true});console.log(JSON.stringify(results.at(-1)));
await p.getByRole('tab',{name:'Security & data policies'}).click();await p.getByLabel('Component').selectOption({index:1});await p.getByLabel('Placement').selectOption({index:1});data=await save('/controls/security','Save data policies');const initialApps=data.team.selected_commands.filter(c=>c.op==='buy_application');results.push({case:'prior security purchase',commands:initialApps});
await p.getByRole('tab',{name:'Host platforms'}).click();await p.getByRole('button',{name:'+ New Host Platform',exact:true}).first().click();await p.locator('.host-platform-form select').first().selectOption('on_prem');await p.getByLabel('Name',{exact:true}).fill('Preservation host race closed');let w=p.waitForResponse(r=>r.url().endsWith('/host-platforms')&&r.request().method()==='POST');await p.getByRole('button',{name:'Create',exact:true}).click();await w;await p.getByText('Preservation host race closed',{exact:true}).click();await p.getByRole('button',{name:'+ Add a Component',exact:true}).click();const cards=p.locator('.catalog-service-card');console.log('cards',await cards.count());await cards.first().getByRole('radio').first().check();w=p.waitForResponse(r=>r.url().endsWith('/controls/security')&&r.request().method()==='PATCH');await p.route('**/platform',async route=>{if(route.request().method()==='GET')await new Promise(r=>setTimeout(r,2000));await route.continue();});await cards.first().getByRole('button',{name:'Provision',exact:true}).click();const provision=await w;results.push({case:'component provision',status:provision.status(),body:await provision.json()});console.log('provision',provision.status());const closeBlocked=await p.getByRole('button',{name:'Close',exact:true}).isDisabled();results.push({case:'close blocked during delayed post-purchase refresh',closeBlocked});if(!closeBlocked)throw Error('Close exposed stale controls');await p.getByRole('button',{name:'Close',exact:true}).click();const afterProvision=await(await p.request.get(prefix+'/controls',{headers})).json();await p.getByRole('tab',{name:'Security & data policies'}).click();data=await save('/controls/security','Save data policies');results.push({case:'host component followed by policy save',before:afterProvision.team.selected_commands.filter(c=>c.op==='buy_application'),after:data.team.selected_commands.filter(c=>c.op==='buy_application')});console.log(JSON.stringify(results.at(-1)));await p.screenshot({path:out+'purchase-loss.png',fullPage:true});
}finally{await writeFile(out+'preservation-results.json',JSON.stringify(results,null,2));await browser.close();}
