import {chromium} from '../../../frontend/node_modules/playwright/index.mjs';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=new URL('.',import.meta.url).pathname,base='http://127.0.0.1:3004';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(60000);
const results=[],diagnostics=[];let negative=false;
page.on('pageerror',e=>diagnostics.push({negative,type:'page',text:e.message}));page.on('console',m=>{if(m.type()==='error')diagnostics.push({negative,type:'console',text:m.text()});});page.on('response',r=>{if(r.status()>=400)diagnostics.push({negative,type:'http',status:r.status(),url:r.url()});});
const pass=(name,data)=>{results.push({name,data});console.log(name,JSON.stringify(data||{}));};
const shot=async name=>page.screenshot({path:out+name+'.png',fullPage:true});
const visit=async route=>{await page.goto(base+route);await page.locator('.product-shell__content').waitFor();};
const save=async (endpoint,label)=>{const p=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='PATCH');await page.getByRole('button',{name:label,exact:true}).click();const r=await p;assert.equal(r.status(),200,await r.text());return r.json();};
try{
 await page.goto(base+'/login');await page.getByLabel('Student ID').fill('M2-101');await page.getByLabel('Password',{exact:true}).fill('StudentPass!2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(base+'/');await page.locator('.product-shell__content').waitFor();
 const token=await page.evaluate(()=>sessionStorage.getItem('mis_sim.access_token'));const headers={Authorization:`Bearer ${token}`};const get=async path=>(await page.request.get(base+'/api'+path,{headers})).json();const me=await get('/auth/me');const pref='/instances/'+me.instance_id;pass('Browser authentication',me.role);
 await page.getByRole('link',{name:/Rollout/}).click();await page.getByRole('slider').first().waitFor();
 const before=await get(pref+'/rollout');pass('Seed deployments',before.team.deployments.map(d=>({id:d.id,unit:d.org_unit})));
 for(let i=0;i<2;i++){await page.getByRole('tab').nth(i).click();await page.getByRole('slider').first().focus();await page.keyboard.press('End');await save('/rollout','Save Changes');}
 let data=await get(pref+'/rollout');assert.equal(data.team.selected_commands.filter(c=>c.op==='train').length,2);pass('Two application drafts preserved',data.team.selected_commands);
 await page.getByRole('tab',{name:'Ownership'}).click();await page.locator('tbody select').first().selectOption('finance');await save('/controls/governance','Save ownership decisions');await page.getByRole('tab').first().click();await save('/rollout','Save Changes');pass('Sibling ownership then rollout save revision synchronized');
 await page.getByRole('link',{name:/Infrastructure/}).click();await page.getByRole('tab',{name:'Security & data policies'}).click();const pol=page.getByLabel('Who can access customer records?');const last=await pol.locator('option').last().getAttribute('value');await pol.selectOption(last);await save('/controls/security','Save data policies');await page.getByRole('tab',{name:'People',exact:true}).click();const hire=page.getByLabel('Hiring option');await hire.selectOption({index:1});data=await save('/controls/people','Save people decisions');assert.equal(data.team.selected_commands.filter(c=>c.op==='communicate').length,before.team.deployments[0].org_unit===before.team.deployments[1].org_unit?1:2);pass('Policy then hiring saves preserve communication and revision');
 await page.reload();await page.getByRole('tab',{name:'Security & data policies'}).click();assert.equal(await pol.inputValue(),last);await shot('security-1280');pass('Security draft survives reload');
 await page.getByRole('tab',{name:'People',exact:true}).click();const unit=before.team.deployments[0].org_unit;await page.getByLabel('Unit').selectOption(unit);await hire.selectOption({index:1});const people=await save('/controls/people','Save people decisions');pass('Partial communication selection plus hiring', {unit,communicationPreserved:people.team.selected_commands.some(c=>c.op==='communicate'&&c.org_unit===unit),commands:people.team.selected_commands});await shot('people-partial');
 for(const width of [1440,1024,720]){await page.setViewportSize({width,height:1000});await visit('/infrastructure');await page.getByRole('tab',{name:'Security & data policies'}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);await shot('security-'+width);await visit('/rollout');await page.getByRole('tab',{name:'Ownership'}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);await shot('ownership-'+width);}pass('Restored controls responsive document widths');
 await page.setViewportSize({width:1280,height:1000});await visit('/infrastructure');await page.getByRole('button',{name:'+ New Host Platform',exact:true}).first().click();await page.locator('.host-platform-form select').first().selectOption('on_prem');await page.getByLabel('Name',{exact:true}).fill('Independent audit host');let wait=page.waitForResponse(r=>r.url().endsWith('/host-platforms')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create',exact:true}).click();let host=(await(await wait).json()).platforms.find(x=>x.name==='Independent audit host');let attach=await page.request.post(base+'/api'+pref+'/host-platforms/'+host.id+'/members',{headers,data:{asset_key:before.team.deployments[0].id,member_kind:'component'}});assert.equal(attach.status(),200);await visit('/rollout');await page.getByRole('button',{name:/^view/}).click();await page.locator('.platform-detail-modal').waitFor();assert.equal(await page.locator('.platform-detail-modal input:not([disabled]),.platform-detail-modal select:not([disabled])').count(),0);assert.equal(await page.getByRole('button',{name:'+ Add a Service',exact:true}).count(),0);await shot('readonly-host');pass('Rollout modal actual host name and member',await page.locator('.platform-detail-modal').innerText());
 await visit('/rollout');const stale=await get(pref+'/controls');await page.request.patch(base+'/api'+pref+'/controls/strategy',{headers,data:{version:1,expected_revision:stale.team.revision,commands:[{key:'review_strategy',op:'declare_strategy',strategy:'cost_leadership'}]}});negative=true;wait=page.waitForResponse(r=>r.url().endsWith('/rollout')&&r.request().method()==='PATCH');await page.getByRole('button',{name:'Save Changes',exact:true}).click();const conflict=await wait;pass('Stale draft save response',{status:conflict.status(),body:await conflict.text(),alert:await page.getByRole('alert').innerText()});await shot('stale-save');negative=false;
 await visit('/review');await page.getByRole('button',{name:'Lock round',exact:true}).waitFor();wait=page.waitForResponse(r=>r.url().endsWith('/review/lock'));await page.getByRole('button',{name:'Lock round',exact:true}).click();assert.equal((await wait).status(),200);await visit('/infrastructure');await page.getByRole('tab',{name:'People',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Save people decisions'}).isDisabled(),true);await page.getByRole('tab',{name:'Security & data policies'}).click();assert.equal(await page.getByRole('button',{name:'Save data policies'}).isDisabled(),true);pass('Locked restored panels read-only');
}finally{await writeFile(out+'results.json',JSON.stringify({results,diagnostics},null,2));await browser.close();}
