import{chromium}from'../../../frontend/node_modules/playwright/index.mjs';import{writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const base='http://127.0.0.1:3004',out=new URL('.',import.meta.url).pathname,b=await chromium.launch(),checks=[],errors=[];let complete=false;const record=(name,data)=>{checks.push({name,data});console.log(name,JSON.stringify(data||{}));};
async function login(id,staff=false,section=null){const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(90000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('409'))errors.push(m.text());});p.on('response',r=>{if(r.status()>=400&&!(r.status()===409&&r.url().endsWith('/auth/login')))errors.push(`${r.status()} ${r.url()}`);});await p.goto(base+'/login');if(staff)await p.getByRole('button',{name:'Staff',exact:true}).click();await p.getByLabel(staff?'Email':'Student ID',{exact:true}).fill(id);await p.getByLabel('Password',{exact:true}).fill(staff?'InstructorPass!2026':'StudentPass!2026');await p.getByRole('button',{name:'Sign in',exact:true}).click();if(section)await p.getByRole('button',{name:section,exact:true}).click();await p.waitForURL(base+'/');await p.locator('.product-shell').waitFor();const headers={Authorization:'Bearer '+await p.evaluate(()=>sessionStorage.getItem('mis_sim.access_token'))};return{p,headers};}
async function api(u,method,path,data,status=200){const r=await u.p.request.fetch(base+'/api'+path,{method,headers:u.headers,data,timeout:180000});assert.equal(r.status(),status,await r.text());return r.json();}
async function action(p,method,suffix,act){const w=p.waitForResponse(r=>r.url().endsWith(suffix)&&r.request().method()===method);await act();const r=await w;assert.ok([200,201].includes(r.status()),await r.text());return r.json();}
try{const staff=await login('m2.instructor.a@example.edu',true),p=staff.p,iid=3,course={id:5},startPath='/instructor/instances/3/start',readyPath='/instructor/instances/3/start-readiness';const readiness=await api(staff,'GET',readyPath),teams=readiness.teams.map(t=>({id:t.team_id,name:t.name}));await p.goto(base+'/instructor/setup');await p.getByLabel('Selected course').selectOption('5');await p.getByRole('button',{name:'Open round controls',exact:true}).waitFor();await p.screenshot({path:out+'success-wide.png',fullPage:true});const body={confirm_instance_id:iid,expected_pack_digest:readiness.pack_digest,team_strategies:teams.map((t,i)=>({team_id:t.id,strategy_key:readiness.strategies[i].key}))};await api(staff,'POST',startPath,body,409);record('UI start succeeds and duplicateAPI conflicts');await p.reload();await p.getByLabel('Selected course').selectOption(String(course.id));await p.getByRole('button',{name:'Open round controls',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Start simulation',exact:true}).count(),0);
const student=await login('M2-101',false,'Start audit section');const controls=await api(student,'GET','/instances/'+iid+'/controls');assert.equal(controls.team.strategy,readiness.strategies[0].key);const dash=await api(student,'GET','/instances/'+iid+'/dashboard');record('Student initial strategy and capital',{strategy:controls.team.strategy,dashboard:dash});await api(student,'GET',readyPath,undefined,403);await api(student,'POST',startPath,body,403);const wrong=await login('m2.instructor.b@example.edu',true);await api(wrong,'GET',readyPath,undefined,403);await api(wrong,'POST',startPath,body,403);record('Student and wrong-owner instructor readiness/start forbidden403');
await student.p.goto(base+'/rollout');await student.p.getByRole('slider').first().focus();await student.p.keyboard.press('End');await action(student.p,'PATCH','/rollout',()=>student.p.getByRole('button',{name:'Save Changes',exact:true}).click());await student.p.goto(base+'/review');await action(student.p,'POST','/review/lock',()=>student.p.getByRole('button',{name:'Lock round',exact:true}).click());await p.getByRole('button',{name:'Open round controls',exact:true}).click();await p.getByLabel('Course').selectOption(String(course.id));const advance=await action(p,'POST','/round-control/advance',()=>p.getByRole('button',{name:'Advance round',exact:true}).click());assert.equal(advance.round,1);await student.p.goto(base+'/debrief');await student.p.locator('.product-shell').waitFor();await student.p.screenshot({path:out+'student-result.png',fullPage:true});record('Student save/lock; instructor UI advances; result visible',{round:advance.round,next:advance.next_round});assert.deepEqual(errors,[]);complete=true;
}finally{await writeFile(out+'continuation-results.json',JSON.stringify({complete,checks,errors},null,2));await b.close();}
